/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#281810",
        "linen-cream": "#F2EFE9",
        "inverse-on-surface": "#f2f1ec",
        "error-container": "#ffdad6",
        "on-secondary-container": "#726250",
        "tertiary": "#0c1c1c",
        "on-tertiary-container": "#889999",
        "primary-fixed-dim": "#dec1b3",
        "on-secondary-fixed": "#25190c",
        "on-secondary-fixed-variant": "#534434",
        "on-secondary": "#ffffff",
        "inverse-surface": "#30312e",
        "background": "#fbf9f4",
        "taupe": "#8D7B68",
        "surface": "#fbf9f4",
        "surface-container": "#f0eee9",
        "on-tertiary-fixed-variant": "#394a4a",
        "inverse-primary": "#dec1b3",
        "secondary-fixed": "#f5dfc8",
        "on-surface": "#1b1c19",
        "gold-leaf": "#C5A059",
        "on-error-container": "#93000a",
        "primary-container": "#3c2a21",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#0e1e1e",
        "secondary-container": "#f5dfc8",
        "on-background": "#1b1c19",
        "surface-container-low": "#f5f3ee",
        "surface-bright": "#fbf9f4",
        "surface-dim": "#dbdad5",
        "on-primary-container": "#aa9084",
        "primary": "#25160e",
        "tertiary-fixed-dim": "#b8cac9",
        "surface-tint": "#705a4f",
        "outline": "#81756f",
        "surface-container-high": "#eae8e3",
        "bone-white": "#F9F7F2",
        "on-primary": "#ffffff",
        "tertiary-container": "#213131",
        "surface-variant": "#e4e2dd",
        "on-surface-variant": "#4f4540",
        "tertiary-fixed": "#d4e6e5",
        "surface-container-highest": "#e4e2dd",
        "error": "#ba1a1a",
        "espresso": "#3C2A21",
        "on-primary-fixed-variant": "#574238",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#d8c3ad",
        "primary-fixed": "#fbdcce",
        "outline-variant": "#d3c3bd",
        "secondary": "#6c5c4a"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit": "8px",
        "container-max": "1440px",
        "section-gap": "128px",
        "margin-edge": "64px",
        "gutter": "32px"
      },
      fontFamily: {
        "serif": ["Playfair Display", "serif"],
        "sans": ["Hanken Grotesk", "sans-serif"],
        "display": ["Playfair Display", "serif"],
        "body": ["Hanken Grotesk", "sans-serif"]
      },
    },
  },
  plugins: [],
}
